import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarPage from "./components/navbar/page";

import FooterPage from "./components/footer/page";
import { ThemeProvider } from "./components/ThemeProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          <NavbarPage />
          <main className="w-full mx-auto px-4">
            {children}
          </main>
          <FooterPage />
        </ThemeProvider>
      </body>
    </html>
  );
}
